# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
#

# zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
#mkdir -p "$(dirname $ZINIT_HOME)"
#git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
# End of zinit
#

# ENV
export PATH=$PATH:$HOME/.local/bin

# Plugins
zi load "zsh-users/zsh-autosuggestions"

zi load "zsh-users/zsh-syntax-highlighting"

zi load "sindresorhus/pure"

zi load "none9632/zsh-sudo"

# End of Plugins
